"""Resumable full-wave azimuth-sweep engine (GUI- and CLI-drivable).

STATE = THE FILESYSTEM, so every failure mode resumes cleanly:
  out/sweeps/<name>/config.json   the sweep definition (written once)
  out/sweeps/<name>/az{ddd}.npz   one file per COMPLETED azimuth,
                                  written atomically (tmp + os.replace -
                                  a killed process can never leave a
                                  half-written azimuth)
  out/sweeps/<name>/status.json   heartbeat + progress for the GUI
  out/sweeps/<name>/run.log       runner stdout
  out/sweeps/<name>/STOP          cooperative stop flag: the GUI Stop
                                  button creates it; checked between
                                  azimuths AND mid-trace via the solver
                                  progress callback (the in-flight
                                  azimuth is discarded and redone on
                                  continue; all saved files are final)
Continue = start again with the same config: completed azimuths are
detected by their files and skipped. Different specimens/configs are
just different sweep directories.

Protocol per azimuth = the VALIDATED rotated-specimen mechanism
(rotation_test.rotated_grid, same as all existing fw_az results):
specimen grains AND c-axes rotate against the fixed probe; labels
solver, order 8, fluid damp 0.02, record to record_factor*D/c.
"""
import argparse
import json
import os
import os as _os, sys as _sys
_sys.path[:0] = [_os.path.join(_os.path.dirname(
    _os.path.dirname(_os.path.abspath(__file__))), _d)
                 for _d in ('core', 'model', 'pipeline', 'fe_crosscheck', 'fw_checks')]
import sys
import time

import numpy as np

sys.path.insert(0, (os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "vendor"))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path[:0] = [os.path.join(sys.path[0], _d)
                for _d in ('core', 'model', 'pipeline', 'fe_crosscheck', 'fw_checks')]

C_REF = 3850.0
SWEEPS = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "out", "sweeps"))


class StopRequested(Exception):
    pass


def _atomic_replace(tmp, dst, critical):
    """os.replace with retries. On Windows, replace FAILS if any other
    process (the GUI polling every 5 s!) briefly holds the target open -
    measured in the wild: PermissionError killed a runner mid-sweep.
    Status files are cosmetic (give up silently after retries); azimuth
    DATA files are the science (retry hard, then raise)."""
    for attempt in range(25):
        try:
            os.replace(tmp, dst)
            return True
        except PermissionError:
            time.sleep(0.2)
    if critical:
        raise PermissionError(f"could not replace {dst} after 5 s of "
                              "retries - is something holding it open?")
    try:
        os.remove(tmp)
    except OSError:
        pass
    return False


DEFAULTS = dict(
    f0_mhz=5.0, ppw=6.0, order=8, az_start=0, az_stop=360, az_step=1,
    sweep_order="progressive",
    # record_factor 2.7 (was 2.2): records reach ~70 us so the post-E1
    # tail observable window (54-66 us, the strongest kappa channel
    # found by the 2026-07-29 trace-mining study) is fully captured.
    # Costs ~23% more per azimuth.
    record_factor=2.7, fluid_damp=0.02, sponge=10, element_d_mm=6.35,
    diameter_mm=100.0, thickness_mm=35.0, n_grains=100, size_cv=0.35,
    concentration=3.93, spatial_corr=0.0, fabric_axis=[1.0, 0.0, 0.0],
    seed=7,
    # rotated_grid frame convention. 'rigid2' = fixed axes rotation
    # (2026-07-29): specimen geometry AND c-axes both rotate by -rot
    # (a true rigid rotation). Sweeps whose config lacks this key were
    # generated by the pre-fix code (axes spun +rot) and must not be
    # continued with the fixed code - see the guard in run().
    axes_convention="rigid2",
    # FD coefficient band (2026-07-31). The optimiser used to stall at
    # peak phase error 4.36e-4; a multi-start solve of the identical
    # objective reaches 5.99e-5. Widening the design band to kh_max 2.0
    # additionally covers 3-5 MHz at ppw 6, where the staircase grid
    # noise lives. MEASURED on 10 antipodal pairs of the seed-11
    # specimen: energy above 3 MHz 68.3 -> 53.0 % (4.0 sigma) and
    # coda/E1 -40.8 -> -42.7 dB (3.3 sigma) for +4.5 % time steps.
    # Timing accuracy does NOT improve (reciprocity unchanged) - better
    # operators fix propagation, not the staircased interface itself.
    # Sweeps whose config predates this key fall back to the exact old
    # single-start kh_max 1.6 coefficients, so they stay reproducible.
    fd_kh_max=2.0,
    # Evaluate the Laguerre tessellation at the rotated solver points
    # instead of nearest-neighbour resampling an already-rasterised
    # label volume (which aliased every grain boundary twice).
    rasterise="single",
)


def sweep_dir(name):
    return os.path.join(SWEEPS, name)


def create(name, **overrides):
    cfg = dict(DEFAULTS)
    cfg.update(overrides)
    cfg["name"] = name
    d = sweep_dir(name)
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, "config.json")
    if not os.path.exists(p):
        with open(p, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=1)
    return p


def load(name_or_path):
    p = (name_or_path if name_or_path.endswith("config.json")
         else os.path.join(sweep_dir(name_or_path), "config.json"))
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def list_sweeps():
    if not os.path.isdir(SWEEPS):
        return []
    out = []
    for n in sorted(os.listdir(SWEEPS)):
        if os.path.exists(os.path.join(SWEEPS, n, "config.json")):
            out.append(n)
    return out


def _bit_reversed_order(n):
    """Progressive (van der Corput) visiting order for n items: every
    prefix of the sequence is near-uniformly spread over the range."""
    if n <= 1:
        return list(range(n))
    bits = (n - 1).bit_length()
    out = []
    for i in range(2 ** bits):
        r = int(format(i, f"0{bits}b")[::-1], 2)
        if r < n:
            out.append(r)
    return out


def azimuths(cfg):
    """Azimuth VISITING order. 'progressive' (default): bit-reversed so
    any partially-complete sweep is maximally spread - and since the
    fabric observables are 180-degree periodic, the half-circle is
    covered finely FIRST (the second half adds independent realization
    averaging, not new pattern geometry). 'sequential': plain order."""
    base = list(range(int(cfg["az_start"]), int(cfg["az_stop"]),
                      int(cfg["az_step"])))
    if cfg.get("sweep_order", "progressive") != "progressive":
        return base
    mid = cfg["az_start"] + 180
    first = [a for a in base if a < mid]
    second = [a for a in base if a >= mid]
    ordered = [first[i] for i in _bit_reversed_order(len(first))]
    ordered += [second[i] for i in _bit_reversed_order(len(second))]
    return ordered


def done_azimuths(cfg):
    d = sweep_dir(cfg["name"])
    return sorted(int(f[2:5]) for f in os.listdir(d)
                  if f.startswith("az") and f.endswith(".npz"))


def pending(cfg):
    done = set(done_azimuths(cfg))
    return [a for a in azimuths(cfg) if a not in done]


def _status(cfg, **kw):
    """Merge-update status.json (atomic). Merging matters: fields like
    sec_per_az are only KNOWN during a run, and a replacing write on
    stop would erase them - the GUI wants the last measured rate to
    show a projected ETA for Continue."""
    p = os.path.join(sweep_dir(cfg["name"]), "status.json")
    s = {}
    if os.path.exists(p):
        try:
            with open(p, encoding="utf-8") as f:
                s = json.load(f)
        except Exception:
            s = {}
    s.update(pid=os.getpid(), heartbeat=time.time(),
             done=len(done_azimuths(cfg)), total=len(azimuths(cfg)))
    s.update({k: v for k, v in kw.items() if v is not None})
    tmp = p + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(s, f)
    _atomic_replace(tmp, p, critical=False)


def _analyse(tr, dt):
    from scipy.signal import hilbert
    e = np.abs(hilbert(tr))
    fs = 1.0 / dt
    k0 = int(2 * 0.100 / C_REF * fs)
    a, b = max(k0 - int(2e-6 * fs), 0), min(k0 + int(2e-6 * fs), len(e))
    k = a + int(np.argmax(e[a:b]))
    E1, t1 = float(e[k]), k * dt
    lo, hi = int(24e-6 * fs), min(int(36e-6 * fs), len(e))
    coda = 20 * np.log10(np.sqrt((e[lo:hi] ** 2).mean()) / E1 + 1e-30)
    # stability tail AFTER E1 has passed (the last-10% convention from
    # the 2.6x-record era straddles E1 at record_factor 2.2 and always
    # read ~0.9); empty window -> nan (record too short to judge)
    k_tail = int((t1 + 3e-6) * fs)
    tail = (float(np.abs(tr[k_tail:]).max() / max(E1, 1e-30))
            if k_tail < len(tr) - 8 else float("nan"))
    return E1, t1, float(coda), tail


def run(cfg):
    # CUDA policy: attempt GPU, report clearly if absent. The specimen
    # builder falls back to CPU on its own; the full-wave solver has no
    # CPU path (194M cells x 9400 steps is GPU work by nature), so
    # without CUDA the sweep stops with a message, not a traceback.
    try:
        import cupy as cp
        ndev = cp.cuda.runtime.getDeviceCount()
        name = cp.cuda.runtime.getDeviceProperties(0)["name"].decode()
        print(f"[sweep] CUDA: {ndev} device(s), using {name}", flush=True)
    except Exception as e:
        _status(cfg, phase="NO CUDA - cannot run")
        print("[sweep] CUDA unavailable ({}: {}). The full-wave solver "
              "needs an NVIDIA GPU; specimen building would fall back "
              "to CPU but the sweep itself cannot run without CUDA."
              .format(type(e).__name__, e), flush=True)
        return

    from scipy import ndimage

    import fdtd
    from rotation_test import rotated_grid
    from specimen import DiskSpecimen

    d = sweep_dir(cfg["name"])
    stop_flag = os.path.join(d, "STOP")
    if os.path.exists(stop_flag):
        os.remove(stop_flag)                    # starting clears old stops

    # Frame-convention guard (2026-07-29 rotated_grid fix): a sweep
    # started under the pre-fix code (no axes_convention key) must not
    # be continued with the fixed code - the two conventions produce
    # physically different specimens per azimuth and would mix in one
    # dataset. Fresh dirs are upgraded in place; partly-done legacy
    # sweeps must be restarted under a new name.
    if cfg.get("axes_convention") != "rigid2":
        if done_azimuths(cfg):
            _status(cfg, phase="LEGACY sweep - cannot continue")
            print("[sweep] config.json has no axes_convention='rigid2': "
                  "this sweep was generated by the pre-2026-07-29 "
                  "rotated_grid (c-axes spun +rot instead of -rot). "
                  "Continuing it with the fixed code would mix "
                  "conventions. Start a NEW sweep instead.", flush=True)
            return
        cfg["axes_convention"] = "rigid2"
        p = os.path.join(d, "config.json")
        tmp = p + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=1)
        _atomic_replace(tmp, p, critical=True)
        print("[sweep] empty sweep dir upgraded to axes_convention="
              "'rigid2'", flush=True)

    f0 = cfg["f0_mhz"] * 1e6
    h = C_REF / f0 / cfg["ppw"]
    print(f"[sweep {cfg['name']}] building specimen (h = {h*1e3:.3f} mm)",
          flush=True)
    # keep the heartbeat alive during the minutes-long build so the GUI
    # does not misread the quiet spell as a dead runner
    import threading
    _stop_hb = threading.Event()

    def _hb():
        while not _stop_hb.is_set():
            _status(cfg, phase=f"building specimen (h = {h*1e3:.2f} mm"
                               ", a few minutes at 5 MHz)")
            _stop_hb.wait(20)
    threading.Thread(target=_hb, daemon=True).start()
    sp = DiskSpecimen(diameter_m=cfg["diameter_mm"] * 1e-3,
                      thickness_m=cfg["thickness_mm"] * 1e-3,
                      n_grains=cfg["n_grains"], size_cv=cfg["size_cv"],
                      concentration=cfg["concentration"],
                      spatial_corr=cfg["spatial_corr"],
                      fabric_axis=tuple(cfg["fabric_axis"]),
                      seed=cfg["seed"])
    build = sp.build(h)
    _stop_hb.set()
    # legacy sweeps (config predating fd_kh_max) get the EXACT old
    # single-start kh_max 1.6 coefficients so they stay reproducible
    _khm = cfg.get("fd_kh_max")
    co = fdtd.optimised_coeffs(cfg["order"],
                               kh_max=1.6 if _khm is None else float(_khm),
                               multistart=_khm is not None)
    _single = cfg.get("rasterise") == "single"
    print(f"[sweep] FD coeffs kh_max "
          f"{1.6 if _khm is None else _khm}"
          f"{'' if _khm is not None else ' (LEGACY single-start)'}; "
          f"rasterise {'single' if _single else 'double (legacy)'}",
          flush=True)

    todo = pending(cfg)
    total = len(azimuths(cfg))
    print(f"[sweep] {len(todo)} of {total} azimuths pending", flush=True)
    times = []
    for i, az in enumerate(todo):
        if os.path.exists(stop_flag):
            print("[sweep] STOP flag found - exiting cleanly. "
                  "All completed azimuths are saved.", flush=True)
            _status(cfg, phase="stopped")
            return
        t0 = time.time()
        _status(cfg, phase=f"az {az}", current_az=az,
                sec_per_az=float(np.mean(times)) if times else None)
        lab, nd, m, axes_rot = rotated_grid(build, h, cfg["sponge"], az,
                                            single_raster=_single)
        nz, nyy = lab.shape[0], lab.shape[1]
        mats = (lab + 1).astype(np.uint8)
        Ct, rho_t = fdtd.material_tables(axes_rot)
        dt = fdtd.safe_dt_labels(mats, Ct, rho_t, h, co, safety=0.5)
        D = nd * h
        nt = int(cfg["record_factor"] * D / C_REF / dt)
        wav = fdtd.ricker(f0, dt, nt)
        dist = ndimage.distance_transform_edt((lab < 0).astype(np.float32))
        dm = np.exp(-cfg["fluid_damp"] * dist).astype(np.float32)
        cz, cy, cx = nz // 2, nyy // 2, nyy // 2
        Rc = nd // 2
        ixp = next(cx + k - 1 for k in range(Rc - 1, 0, -1)
                   if lab[cz, cy, cx + k] >= 0)
        er = max(int(cfg["element_d_mm"] * 1e-3 / 2 / h), 1)
        pts = [(cz + dz, cy + dy, ixp) for dy in range(-er, er + 1)
               for dz in range(-er, er + 1)
               if dy * dy + dz * dz <= er * er
               and lab[cz + dz, cy + dy, ixp] >= 0]
        w = 1.0 / len(pts)

        def prog(frac):
            _status(cfg, phase=f"az {az} ({100*frac:.0f}%)",
                    current_az=az,
                    sec_per_az=float(np.mean(times)) if times else None)
            if os.path.exists(stop_flag):
                raise StopRequested()

        try:
            tr = np.asarray(fdtd.forward_fused_labels(
                lab, axes_rot, h, dt, nt, [(p, w) for p in pts], wav,
                [(pts, np.full(len(pts), w))], order=cfg["order"],
                coeffs=co, sponge_width=cfg["sponge"], damp_mask=dm,
                progress=prog), float).ravel()
        except StopRequested:
            print(f"[sweep] STOP mid-trace at az {az} - this azimuth "
                  "will be redone on continue; all saved files are "
                  "final.", flush=True)
            _status(cfg, phase="stopped")
            return
        E1, t1, coda, tail = _analyse(tr, dt)
        # tmp name MUST end in .npz: np.savez silently appends the
        # extension otherwise and the atomic rename then fails
        tmp = os.path.join(d, f"az{az:03d}.tmp.npz")
        np.savez(tmp, trace=tr.astype(np.float32), dt=dt, f0=f0,
                 az_deg=az, E1=E1, t1_s=t1, coda_db=coda, tail=tail,
                 h=h, order=cfg["order"], ppw=cfg["ppw"],
                 fluid_damp=cfg["fluid_damp"], seed=cfg["seed"])
        _atomic_replace(tmp, os.path.join(d, f"az{az:03d}.npz"),
                        critical=True)
        el = time.time() - t0
        times.append(el)
        eta_h = np.mean(times) * (len(todo) - i - 1) / 3600
        print(f"[sweep] az {az:3d}: coda {coda:6.1f} dB, E1 {E1:.4g}, "
              f"ToF {t1*1e6:.3f} us, tail {tail:.3f} "
              f"({'STABLE' if tail < 0.5 else 'CHECK'}) "
              f"| {el:.0f}s, ETA {eta_h:.1f} h", flush=True)
    _status(cfg, phase="complete")
    print("[sweep] COMPLETE", flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", help="sweep name or config.json path")
    ap.add_argument("--new", help="create a sweep with this name")
    ap.add_argument("--set", nargs="*", default=[],
                    help="key=value overrides for --new")
    args = ap.parse_args()
    if args.new:
        kw = {}
        for kv in args.set:
            k, v = kv.split("=", 1)
            try:
                kw[k] = json.loads(v)
            except json.JSONDecodeError:
                kw[k] = v
        p = create(args.new, **kw)
        print(f"created {p}")
        return
    if args.run:
        run(load(args.run))


if __name__ == "__main__":
    main()
